<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
            ['name_en' => "Riyadh", 'name_ar' => "الرياض", 'country_id' => 1],
            ['name_en' => "Makkah", 'name_ar' => "مكة", 'country_id' => 1],
            ['name_en' => "Dammam", 'name_ar' => "الدمام", 'country_id' => 1],
            ['name_en' => "Jeddah", 'name_ar' => "جدة", 'country_id' => 1],
            ['name_en' => "Al-Abwa", 'name_ar' => "الابواء", 'country_id' => 1],
            ['name_en' => "Al Artaweeiyah", 'name_ar' => "الأرطاوية", 'country_id' => 1],
            ['name_en' => "Badr", 'name_ar' => "بدر", 'country_id' => 1],
            ['name_en' => "Baljursashi", 'name_ar' => "بلجرشي", 'country_id' => 1],
            ['name_en' => "Bisha", 'name_ar' => "بيشة", 'country_id' => 1],
            ['name_en' => "Bareg", 'name_ar' => "بارق", 'country_id' => 1],
            ['name_en' => "Buraydah", 'name_ar' => "بريدة", 'country_id' => 1],
            ['name_en' => "Al Bahah", 'name_ar' => "الباحة", 'country_id' => 1],
            ['name_en' => "Buqqa", 'name_ar' => "بقعاء", 'country_id' => 1],
            ['name_en' => "Dahran", 'name_ar' => "الظهران", 'country_id' => 1],
            ['name_en' => "Dhurma", 'name_ar' => "ضرماء", 'country_id' => 1],
            ['name_en' => "Dahban", 'name_ar' => "ذهبان", 'country_id' => 1],
            ['name_en' => "Diriyah", 'name_ar' => "الدرعية", 'country_id' => 1],
            ['name_en' => "Duba", 'name_ar' => "ضباء", 'country_id' => 1],
            ['name_en' => "Dumat Al-Jandal", 'name_ar' => "دومة الجندل", 'country_id' => 1],
            ['name_en' => "Dawadmi", 'name_ar' => "الدوادمي", 'country_id' => 1],
            ['name_en' => "Farasan", 'name_ar' => "فرسان", 'country_id' => 1],
            ['name_en' => "Gatgat", 'name_ar' => "الغطاط", 'country_id' => 1],
            ['name_en' => "Gerrha", 'name_ar' => "الجرهاء", 'country_id' => 1],
            ['name_en' => "Gurayat", 'name_ar' => "القريات", 'country_id' => 1],
            ['name_en' => "Al-Gwei'iyyah", 'name_ar' => "القويعية", 'country_id' => 1],
            ['name_en' => "Hutat Sudair", 'name_ar' => "حوطة سدير", 'country_id' => 1],
            ['name_en' => "Habala", 'name_ar' => "الحبلة", 'country_id' => 1],
            ['name_en' => "Hajrah", 'name_ar' => "الهجرة", 'country_id' => 1],
            ['name_en' => "Haql", 'name_ar' => "حقل", 'country_id' => 1],
            ['name_en' => "AlHareeq", 'name_ar' => "الحريق", 'country_id' => 1],
            ['name_en' => "Harmah", 'name_ar' => "حرمه", 'country_id' => 1],
            ['name_en' => "Ha'il", 'name_ar' => "حائل", 'country_id' => 1],
            ['name_en' => "Hotat Bani Tamim", 'name_ar' => "حوطة بني تميم", 'country_id' => 1],
            ['name_en' => "Hofuf", 'name_ar' => "هفوف", 'country_id' => 1],
            ['name_en' => "Huraymila", 'name_ar' => "حريملاء", 'country_id' => 1],
            ['name_en' => "Hafr Al-Batin", 'name_ar' => "حفر الباطن", 'country_id' => 1],
            ['name_en' => "Jabal Umm al Ru'us", 'name_ar' => "جبل أم الرؤوس", 'country_id' => 1],
            ['name_en' => "Jalajil", 'name_ar' => "جلاجل", 'country_id' => 1],
            ['name_en' => "Al Jawf", 'name_ar' => "الجوف", 'country_id' => 1],
            ['name_en' => "Jizan", 'name_ar' => "جيزان", 'country_id' => 1],
            ['name_en' => "Jizan Economic City", 'name_ar' => "المدينة الاقتصادية بجيزان", 'country_id' => 1],
            ['name_en' => "Jubail", 'name_ar' => "الجبيل", 'country_id' => 1],
            ['name_en' => "Khafji", 'name_ar' => "الخفجي", 'country_id' => 1],
            ['name_en' => "Khaybar", 'name_ar' => "خيبر", 'country_id' => 1],
            ['name_en' => "King Abdullah Economic City", 'name_ar' => "مدينة الملك عبدالله الاقتصادية", 'country_id' => 1],
            ['name_en' => "Khamis Mushayt", 'name_ar' => "خميس مشيط", 'country_id' => 1],
            ['name_en' => "Al Kharj", 'name_ar' => "الخرج", 'country_id' => 1],
            ['name_en' => "Khobar", 'name_ar' => "الخبر", 'country_id' => 1],
            ['name_en' => "Layla", 'name_ar' => "ليلى", 'country_id' => 1],
            ['name_en' => "Al Lith", 'name_ar' => "الليث", 'country_id' => 1],
            ['name_en' => "Al Majma'ah", 'name_ar' => "المجمعه", 'country_id' => 1],
            ['name_en' => "Mastoorah", 'name_ar' => "مستورة", 'country_id' => 1],
            ['name_en' => "Al Mikhwah", 'name_ar' => "المخواة", 'country_id' => 1],
            ['name_en' => "Al-Mubarraz", 'name_ar' => "المبرز", 'country_id' => 1],
            ['name_en' => "Medina", 'name_ar' => "المدينة المنورة", 'country_id' => 1],
            ['name_en' => "Muzahmiyyah", 'name_ar' => "المزاحمية", 'country_id' => 1],
            ['name_en' => "Najran", 'name_ar' => "نجران", 'country_id' => 1],
            ['name_en' => "Al-Namas", 'name_ar' => "النماص", 'country_id' => 1],
            ['name_en' => "Omloj", 'name_ar' => "أملج", 'country_id' => 1],
            ['name_en' => "Al-Omran", 'name_ar' => "العمران", 'country_id' => 1],
            ['name_en' => "Al-Oyoon", 'name_ar' => "العيون", 'country_id' => 1],
            ['name_en' => "Qadeimah", 'name_ar' => "القضيمة", 'country_id' => 1],
            ['name_en' => "Qatif", 'name_ar' => "القطيف", 'country_id' => 1],
            ['name_en' => "Qaisumah", 'name_ar' => "القيصومة", 'country_id' => 1],
            ['name_en' => "AlQunfudah", 'name_ar' => "القنفذة", 'country_id' => 1],
            ['name_en' => "Rabigh", 'name_ar' => "رابغ", 'country_id' => 1],
            ['name_en' => "Rafha", 'name_ar' => "رفحاء", 'country_id' => 1],
            ['name_en' => "Ar Rass", 'name_ar' => "الرس", 'country_id' => 1],
            ['name_en' => "Ras Tanura", 'name_ar' => "راس تنورة", 'country_id' => 1],
            ['name_en' => "Riyadh Alkhabra", 'name_ar' => "رياض الخبراء", 'country_id' => 1],
            ['name_en' => "Rumailah", 'name_ar' => "الرميلة", 'country_id' => 1],
            ['name_en' => "Sabt Al Alaya", 'name_ar' => "سبت العلايا", 'country_id' => 1],
            ['name_en' => "Saihat", 'name_ar' => "سيهات", 'country_id' => 1],
            ['name_en' => "Safwa", 'name_ar' => "صفوى", 'country_id' => 1],
            ['name_en' => "Sakakah", 'name_ar' => "سكاكا", 'country_id' => 1],
            ['name_en' => "Sharurah", 'name_ar' => "شرورة", 'country_id' => 1],
            ['name_en' => "Shaqraa", 'name_ar' => "شقراء", 'country_id' => 1],
            ['name_en' => "Shaybah", 'name_ar' => "شيبة", 'country_id' => 1],
            ['name_en' => "As Sulayyil", 'name_ar' => "السليل", 'country_id' => 1],
            ['name_en' => "Taif", 'name_ar' => "الطائف", 'country_id' => 1],
            ['name_en' => "Tabuk", 'name_ar' => "تبوك", 'country_id' => 1],
            ['name_en' => "Tanomah", 'name_ar' => "تنومة", 'country_id' => 1],
            ['name_en' => "Tarout", 'name_ar' => "ثاروت", 'country_id' => 1],
            ['name_en' => "Thadiq", 'name_ar' => "ثادق", 'country_id' => 1],
            ['name_en' => "Thuwal", 'name_ar' => "ثول", 'country_id' => 1],
            ['name_en' => "Thuqbah", 'name_ar' => "الثقبة", 'country_id' => 1],
            ['name_en' => "Turaif", 'name_ar' => "طريف", 'country_id' => 1],
            ['name_en' => "Tabarjal", 'name_ar' => "طبرجل", 'country_id' => 1],
            ['name_en' => "Udhailiyah", 'name_ar' => "العضيلية", 'country_id' => 1],
            ['name_en' => "Al-'Ula", 'name_ar' => "العلا", 'country_id' => 1],
            ['name_en' => "Um Al-Sahek", 'name_ar' => "أم الساهك", 'country_id' => 1],
            ['name_en' => "Unaizah", 'name_ar' => "عنيزة", 'country_id' => 1],
            ['name_en' => "Uqair", 'name_ar' => "عقير", 'country_id' => 1],
            ['name_en' => "'Uyayna", 'name_ar' => "'العيينة", 'country_id' => 1],
            ['name_en' => "Uyun Aljiwa", 'name_ar' => "عيون الجواء", 'country_id' => 1],
            ['name_en' => "Wadi Aldawasir", 'name_ar' => "وادي الدواسر", 'country_id' => 1],
            ['name_en' => "Al Wajh", 'name_ar' => "الوجه", 'country_id' => 1],
            ['name_en' => "Yanbu", 'name_ar' => "ينبع", 'country_id' => 1],
            ['name_en' => "Az Zaimah", 'name_ar' => "الزيمة", 'country_id' => 1],
            ['name_en' => "Zulfi", 'name_ar' => "الزلفي", 'country_id' => 1],
            /***********************End of Saudi Cities*****************************/
            /*********************Start of Emirati Cities***************************/
            ['name_en' => "Dubai", 'name_ar' => "دبي", 'country_id' => 2],
            ['name_en' => "Abu Dhabi", 'name_ar' => "ابو ظبي", 'country_id' => 2],
            ['name_en' => "Sharja", 'name_ar' => "الشارقة", 'country_id' => 2],
            ['name_en' => "Al-Ain", 'name_ar' => "العين", 'country_id' => 2],
            ['name_en' => "Ajman", 'name_ar' => "عجمان", 'country_id' => 2],
            ['name_en' => "Ras Alkhaima", 'name_ar' => "راس الخيمة", 'country_id' => 2],
            ['name_en' => "Al- Fujaira", 'name_ar' => "الفجيرة", 'country_id' => 2],
            ['name_en' => "Um Al - Quwain", 'name_ar' => "أم القيوين", 'country_id' => 2],
            ['name_en' => "Ad-haid", 'name_ar' => "الذيد", 'country_id' => 2],
            ['name_en' => "Al-Bataeh", 'name_ar' => "البطائح", 'country_id' => 2],
            ['name_en' => "Alhamriyah", 'name_ar' => "الحمرية", 'country_id' => 2],
            ['name_en' => "Al-Madam", 'name_ar' => "المدام", 'country_id' => 2],
            ['name_en' => "Diba Alfujayrah", 'name_ar' => "دبا الفجيرة", 'country_id' => 2],
            ['name_en' => "Diba Alhisn", 'name_ar' => "دبا الحصن", 'country_id' => 2],
            ['name_en' => "Hata", 'name_ar' => "حتا", 'country_id' => 2],
            ['name_en' => "Kalba", 'name_ar' => "كلباء", 'country_id' => 2],
            ['name_en' => "Mileihah", 'name_ar' => "مليحة", 'country_id' => 2],
            /*****************End of emirati cities*********************************/
            /****************Start of Kuwaiti Cities ***************************/
            ['name_en' => "Abdullah Mubarak Alsubah", 'name_ar' => "مدينة عبدالله المبارك الصباح", 'country_id' => 3],
            ['name_en' => "Al-Ahmadi", 'name_ar' => "الأحمدي", 'country_id' => 3],
            ['name_en' => "Al Farwaniyah", 'name_ar' => "الفروانية", 'country_id' => 3],
            ['name_en' => "Al Fintas", 'name_ar' => "الفنطاس", 'country_id' => 3],
            ['name_en' => "Al Firdaws", 'name_ar' => "الفردوس", 'country_id' => 3],
            ['name_en' => "Ali Sabah As-Salem", 'name_ar' => "مدينة علي صباح السالم", 'country_id' => 3],
            ['name_en' => "Al Jahra", 'name_ar' => "الجهراء", 'country_id' => 3],
            ['name_en' => "Kuwait", 'name_ar' => "الكويت", 'country_id' => 3],
            ['name_en' => "Al-Manqaf", 'name_ar' => "المنقف", 'country_id' => 3],
            ['name_en' => "Ash-Shuaibah", 'name_ar' => "الشعيبة", 'country_id' => 3],
            ['name_en' => "As-Sulaybikhat", 'name_ar' => "الصليبيخات", 'country_id' => 3],
            ['name_en' => "As-Sulaybiyah", 'name_ar' => "الصليبية", 'country_id' => 3],
            ['name_en' => "Hawalli", 'name_ar' => "حولي", 'country_id' => 3],
            ['name_en' => "Jaber Al-Ahmad", 'name_ar' => "مدينة جابر الاحمد", 'country_id' => 3],
            ['name_en' => "Janub Al-Kuwait", 'name_ar' => "جنوب الكويت", 'country_id' => 3],
            ['name_en' => "Mubarak Al-kabir", 'name_ar' => "مدينة مبارك الجابر", 'country_id' => 3],
            ['name_en' => "Sabhan as-Sinaiyah", 'name_ar' => "صبحان الصناعية", 'country_id' => 3],
            /************************End of Kuwaiti Cities************************/
            /********************************* Start Of Bahraini Cities ******************************/
            ['name_en' => "Al-Budayyi", 'name_ar' => "البديع - الدراز", 'country_id' => 4],
            ['name_en' => "Al-Hadd", 'name_ar' => "الحد", 'country_id' => 4],
            ['name_en' => "A'ali", 'name_ar' => "عالي", 'country_id' => 4],
            ['name_en' => "Al-Malikiyah", 'name_ar' => "كرزكان - المالكية", 'country_id' => 4],
            ['name_en' => "Almanamah", 'name_ar' => "المنامة", 'country_id' => 4],
            ['name_en' => "Al-Muharraq", 'name_ar' => "المحرق", 'country_id' => 4],
            ['name_en' => "Ar-Rifa", 'name_ar' => "الرفاع", 'country_id' => 4],
            ['name_en' => "Jidd Hafs", 'name_ar' => "جد حفص", 'country_id' => 4],
            ['name_en' => "Madinat Hamad", 'name_ar' => "مدينة حمد", 'country_id' => 4],
            ['name_en' => "Madinat Isa", 'name_ar' => "مدينة عيسى", 'country_id' => 4],
            ['name_en' => "Sitrah", 'name_ar' => "سترة", 'country_id' => 4],
            /*************************** End of Bahraini Cities ******************************/
            /***************************** start of Omani Cities **************************/
            ['name_en' => "Adam", 'name_ar' => "ادم", 'country_id' => 5],
            ['name_en' => "Ad-Dariz", 'name_ar' => "الدريز", 'country_id' => 5],
            ['name_en' => "Al-Amart", 'name_ar' => "العامرات", 'country_id' => 5],
            ['name_en' => "Al-Araqi", 'name_ar' => "العراقي", 'country_id' => 5],
            ['name_en' => "Al-Ashkharah", 'name_ar' => "الاشخرة", 'country_id' => 5],
            ['name_en' => "Al-Awabi", 'name_ar' => "العوابي", 'country_id' => 5],
            ['name_en' => "Al-Budayah", 'name_ar' => "البداية", 'country_id' => 5],
            ['name_en' => "Al-Buraymi", 'name_ar' => "البريمي", 'country_id' => 5],
            ['name_en' => "Al-Ghalil", 'name_ar' => "الغليل", 'country_id' => 5],
            ['name_en' => "Al-Hamra", 'name_ar' => "الحمراء", 'country_id' => 5],
            ['name_en' => "Al-Huwayl", 'name_ar' => "الحويل", 'country_id' => 5],
            ['name_en' => "Alkamil wal-wafi", 'name_ar' => "الكامل والوافي", 'country_id' => 5],
            ['name_en' => "Al-khabura", 'name_ar' => "الخابورة", 'country_id' => 5],
            ['name_en' => "Al-Maghsar", 'name_ar' => "المغسر", 'country_id' => 5],
            ['name_en' => "Al-Maghsar", 'name_ar' => "المصنعة", 'country_id' => 5],
            ['name_en' => "al-mintirib", 'name_ar' => "المنترب", 'country_id' => 5],
            ['name_en' => "Almudaibi", 'name_ar' => "المضيبي", 'country_id' => 5],
            ['name_en' => "Al-muladdah", 'name_ar' => "الملدة", 'country_id' => 5],
            ['name_en' => "Ar-Rumays", 'name_ar' => "الرميس", 'country_id' => 5],
            ['name_en' => "Ar-Rustaq", 'name_ar' => "الرستاق", 'country_id' => 5],
            ['name_en' => "As-Sib", 'name_ar' => "السيب", 'country_id' => 5],
            ['name_en' => "As-Subaykhi", 'name_ar' => "الصبيخي", 'country_id' => 5],
            ['name_en' => "As-Suwadi as-Sahil", 'name_ar' => "السوادي الساحل", 'country_id' => 5],
            ['name_en' => "As-Suwaiq", 'name_ar' => "السويق", 'country_id' => 5],
            ['name_en' => "As-Suwamhan", 'name_ar' => "الصومحان", 'country_id' => 5],
            ['name_en' => "Bahla", 'name_ar' => "بهلاء", 'country_id' => 5],
            ['name_en' => "Barka", 'name_ar' => "بركاء", 'country_id' => 5],
            ['name_en' => "Bawshar", 'name_ar' => "بوشر", 'country_id' => 5],
            ['name_en' => "Birkat AlMawz", 'name_ar' => "بركة الموز", 'country_id' => 5],
            ['name_en' => "Danak", 'name_ar' => "ضنك", 'country_id' => 5],
            ['name_en' => "Diba Al-Bay'ah", 'name_ar' => "دباء البيعة", 'country_id' => 5],
            ['name_en' => "Dil Al-Abd as-Salam", 'name_ar' => "ديل ال عبدالسلام", 'country_id' => 5],
            ['name_en' => "Diyan al-Bu Sa'id", 'name_ar' => "ضيان البوسعيد", 'country_id' => 5],
            ['name_en' => "Fanja", 'name_ar' => "فنجا", 'country_id' => 5],
            ['name_en' => "Ghadfan", 'name_ar' => "غضفان", 'country_id' => 5],
            ['name_en' => "Hayma", 'name_ar' => "هيماء", 'country_id' => 5],
            ['name_en' => "Hilf", 'name_ar' => "حلف", 'country_id' => 5],
            ['name_en' => "Ibra", 'name_ar' => "إبراء", 'country_id' => 5],
            ['name_en' => "Ibri", 'name_ar' => "عبري", 'country_id' => 5],
            ['name_en' => "Izki", 'name_ar' => "إزكي", 'country_id' => 5],
            ['name_en' => "Ja'alan Bani Bu Ali", 'name_ar' => "جعلان بني ابو علي", 'country_id' => 5],
            ['name_en' => "Ja'alan Bani Bu Hasan", 'name_ar' => "جعلان بني بو حسن", 'country_id' => 5],
            ['name_en' => "Khadra Al Bu Rashid", 'name_ar' => "خضراء ال بورشيد", 'country_id' => 5],
            ['name_en' => "Khadra as-Sa'd", 'name_ar' => "خضراء ال سعد", 'country_id' => 5],
            ['name_en' => "Khasab", 'name_ar' => "خصب", 'country_id' => 5],
            ['name_en' => "Liwa", 'name_ar' => "لوى", 'country_id' => 5],
            ['name_en' => "Manah", 'name_ar' => "منح", 'country_id' => 5],
            ['name_en' => "Masqat", 'name_ar' => "مسقط", 'country_id' => 5],
            ['name_en' => "Matrah", 'name_ar' => "مطرح", 'country_id' => 5],
            ['name_en' => "Mirbat", 'name_ar' => "مرباط", 'country_id' => 5],
            ['name_en' => "Mukhaylif", 'name_ar' => "مخيليف", 'country_id' => 5],
            ['name_en' => "Murtafat Saham", 'name_ar' => "مرتفعات صحم", 'country_id' => 5],
            ['name_en' => "Nakhal", 'name_ar' => "نخل", 'country_id' => 5],
            ['name_en' => "Nizwa", 'name_ar' => "نزوى", 'country_id' => 5],
            ['name_en' => "Qarn Al-'Alam", 'name_ar' => "قرن العلم", 'country_id' => 5],
            ['name_en' => "Qurrayat", 'name_ar' => "قريات", 'country_id' => 5],
            ['name_en' => "Saham", 'name_ar' => "صحم", 'country_id' => 5],
            ['name_en' => "Salalah", 'name_ar' => "صلالة", 'country_id' => 5],
            ['name_en' => "Samad ash-Shan", 'name_ar' => "سمد الشأن", 'country_id' => 5],
            ['name_en' => "Samail", 'name_ar' => "سمائل", 'country_id' => 5],
            ['name_en' => "Sanaw", 'name_ar' => "سناو", 'country_id' => 5],
            ['name_en' => "Shinas", 'name_ar' => "شناص", 'country_id' => 5],
            ['name_en' => "Suhar", 'name_ar' => "صحار", 'country_id' => 5],
            ['name_en' => "Taqah", 'name_ar' => "طاقة", 'country_id' => 5],
            ['name_en' => "Wadi Say", 'name_ar' => "وادي صاي", 'country_id' => 5],
            ['name_en' => "Wudam as-Sahil", 'name_ar' => "ودام الساحل", 'country_id' => 5],
            ['name_en' => "Yanqul", 'name_ar' => "ينقل", 'country_id' => 5],
        ]);
    }
}
